
<wandb.sdk.wandb_run.Run object at 0x2a5786c10>
tensor([[ 0.3425, -5.4122, -0.1540,  ...,  0.0481,  2.0108,  0.1281],
        [ 0.1005,  2.9271,  2.4612,  ...,  0.6467,  0.9666,  1.1573],
        [ 0.2932, -2.5514,  0.9822,  ...,  0.8633,  1.1458, -0.1912],
        ...,
        [ 0.4778, -1.1280,  0.5509,  ...,  0.5255, -0.6182,  1.0421],
        [-0.2868,  0.0290,  0.6690,  ...,  0.5431, -0.4426,  0.0254],
        [-0.2972, -0.2239,  0.7070,  ...,  0.2101, -0.2692,  0.7303]],
       grad_fn=<AddBackward0>)
torch.Size([10, 3000])
tensor([-1294.2571], grad_fn=<AddBackward0>)
tensor([[ 0.3425],
        [-5.4122],
        [-0.1540],
        ...,
        [ 0.2101],
        [-0.2692],
        [ 0.7303]], grad_fn=<ViewBackward0>)
torch.Size([30000, 1])
DataBatch(edge_index=[2, 179540], pos=[30000, 2], mask=[30000], eigvals=[30000], n_observed=[10], n_unobserved=[10], batch=[30000], ptr=[11], x=[30000, 1])
tensor([[-1.6668],
        [-9.4632],
        [-1.1740],
        ...,
        [-0.6602],
        [-2.5479],
        [ 0.8673]], grad_fn=<AddBackward0>)
tensor([[ 0.3425],
        [-5.4122],
        [-0.1540],
        ...,
        [ 0.2101],
        [-0.2692],
        [ 0.7303]], grad_fn=<ViewBackward0>)
tensor([-647.1285], grad_fn=<MulBackward0>)
tensor(10361.6328, grad_fn=<MulBackward0>)
tensor([914.5638], grad_fn=<AddBackward0>)
tensor(-9644.7617, grad_fn=<MulBackward0>)
0
tensor(-16120587., grad_fn=<MulBackward0>)
tensor(1.0000e-04, grad_fn=<ExpBackward0>)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'noise_var' is not defined
tensor(-500.0000, grad_fn=<NegBackward0>)
tensor(-500.0000, grad_fn=<NegBackward0>)
tensor([[ 0.1002],
        [-0.0055],
        [ 0.3931],
        ...,
        [ 0.2628],
        [ 0.1988],
        [ 0.2063]])
tensor([[ 0.1002],
        [-0.0055],
        [ 0.3931],
        ...,
        [ 0.2628],
        [ 0.1988],
        [ 0.2063]])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'get_bias' is not defined
Data(x=[3000, 1], edge_index=[2, 17954], pos=[3000, 2], mask=[3000], eigvals=[3000], n_observed=2250.0, n_unobserved=750.0)
tensor([[-1.3574],
        [-1.2948],
        [-1.3574],
        ...,
        [-1.3842],
        [-1.3574],
        [-1.4087]], grad_fn=<AddBackward0>)
tensor([[-1.3574],
        [-1.2948],
        [-1.3574],
        ...,
        [-1.3842],
        [-1.3574],
        [-1.4087]], grad_fn=<AddBackward0>)
1e-07
1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
NameError: name 'FlexLayer' is not defined
ModuleList(
  (0): FlexLayer()
)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'self' is not defined
3000
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'self' is not defined
Parameter containing:
tensor([-0.8989,  0.3732, -0.1236,  ..., -0.8628, -0.6135, -0.1547],
       requires_grad=True)
3000
10
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'diag_param' is not defined
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'self' is not defined
Parameter containing:
tensor([ 0.1002, -0.0055,  0.3931,  ...,  0.2628,  0.1988,  0.2063],
       requires_grad=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'diag_param' is not defined
Parameter containing:
tensor([ 0.8297, -0.3969, -0.9590,  ...,  0.4889, -0.3612,  0.7226],
       requires_grad=True)
3000
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'self' is not defined
Parameter containing:
tensor([-0.8989,  0.3732, -0.1236,  ..., -0.8628, -0.6135, -0.1547],
       requires_grad=True)
Parameter containing:
tensor([ 0.8297, -0.3969, -0.9590,  ...,  0.4889, -0.3612,  0.7226],
       requires_grad=True)
Data(edge_index=[2, 17954], pos=[3000, 2], mask=[3000], eigvals=[3000], n_observed=2250.0, n_unobserved=750.0)
DataBatch(edge_index=[2, 179540], pos=[30000, 2], mask=[30000], eigvals=[30000], n_observed=[10], n_unobserved=[10], batch=[30000], ptr=[11])
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'self' is not defined
DataBatch(edge_index=[2, 179540], pos=[30000, 2], mask=[30000], eigvals=[30000], n_observed=[10], n_unobserved=[10], batch=[30000], ptr=[11])
10
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/uc291369/graph-DGMRF/.venv/lib/python3.11/site-packages/torch_geometric/data/batch.py", line 101, in from_data_list
    add_batch=not isinstance(data_list[0], Batch),
                             ~~~~~~~~~^^^
IndexError: list index out of range
DataBatch(edge_index=[2, 17954], pos=[3000, 2], mask=[3000], eigvals=[3000], n_observed=[1], n_unobserved=[1], batch=[3000], ptr=[2])
DataBatch(edge_index=[2, 35908], pos=[6000, 2], mask=[6000], eigvals=[6000], n_observed=[2], n_unobserved=[2], batch=[6000], ptr=[3])
DataBatch(edge_index=[2, 17954], pos=[3000, 2], mask=[3000], eigvals=[3000], n_observed=[1], n_unobserved=[1], batch=[3000], ptr=[2])
ModuleList(
  (0): FlexLayer()
)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/uc291369/graph-DGMRF/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uc291369/graph-DGMRF/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uc291369/graph-DGMRF/layers/linear.py", line 36, in forward
    weighted_repr = self.weight_self_representation(x)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uc291369/graph-DGMRF/layers/flex.py", line 88, in weight_self_representation
    return (x.view(-1,self.num_nodes)*torch.exp(
            ^^^^^^
AttributeError: 'NoneType' object has no attribute 'view'
FlexLayer()
DataBatch(edge_index=[2, 17954], pos=[3000, 2], mask=[3000], eigvals=[3000], n_observed=[1], n_unobserved=[1], batch=[3000], ptr=[2])
tensor([[   0,    0,    0,  ..., 2999, 2999, 2999],
        [ 581,  647, 1212,  ..., 2210, 2227, 2398]])
tensor([[-0.3998,  0.5111,  0.3431,  ..., -1.6101,  0.0818,  2.2662],
        [ 0.8432, -0.5477,  0.0399,  ..., -0.9076, -1.5172, -1.1077],
        [-1.2916, -0.1834, -0.1038,  ...,  0.0417, -0.5140, -1.0895],
        ...,
        [ 0.3371, -0.3236, -0.2952,  ..., -0.9242, -0.1143,  1.9565],
        [-0.5788, -1.3904, -0.3390,  ...,  0.7426,  0.1891, -0.0439],
        [ 1.0438,  0.3131,  0.3548,  ...,  1.0547,  0.0754,  0.2753]],
       grad_fn=<MulBackward0>)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/uc291369/graph-DGMRF/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uc291369/graph-DGMRF/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uc291369/graph-DGMRF/layers/linear.py", line 36, in forward
    weighted_repr = self.weight_self_representation(x)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uc291369/graph-DGMRF/layers/flex.py", line 88, in weight_self_representation
    return (x.view(-1,self.num_nodes)*torch.exp(
            ^^^^^^
AttributeError: 'NoneType' object has no attribute 'view'
tensor([[-0.3998],
        [ 0.5111],
        [ 0.3431],
        ...,
        [ 1.0547],
        [ 0.0754],
        [ 0.2753]], grad_fn=<ViewBackward0>)
tensor([[-2.3176],
        [ 2.3464],
        [ 1.9430],
        ...,
        [ 6.5365],
        [ 0.4294],
        [ 1.8378]], grad_fn=<AddBackward0>)
'raw_data/wtk_site_metadata.csv'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/uc291369/graph-DGMRF/.venv/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1977, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uc291369/graph-DGMRF/.venv/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uc291369/graph-DGMRF/.venv/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: raw_data/wtk_site_metadata.csv not found.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
